project = "lumpy-space-pirate"
service_account_email = "demo-service-account@lumpy-space-pirate.iam.gserviceaccount.com"
startup_script_username = "realsww123"
github_owner = "sungchun12"
github_branch_name = "master"
