project = "test-demo-257714"
service_account_email = "demo-service-account@test-demo-257714.iam.gserviceaccount.com"
startup_script_username = "realsww123"
github_owner = "sungchun12"
github_branch_name = "master"
